services:
  # Backend Service
  - type: web
    name: tictactoe-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: tictactoe-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CORS_ORIGIN
        value: https://tictactoe-client.onrender.com

  # Frontend Service
  - type: web
    name: tictactoe-client
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://tictactoe-server.onrender.com/api

databases:
  - name: tictactoe-db
    plan: free


